apiVersion: v1
kind: Namespace
metadata:
  name: cba
  labels:
    name: cba
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: afl-cba-customerinfo-deployment
  namespace: cba
spec:
  replicas: 2
  selector:
    matchLabels:
      app: afl-cba-customerinfo
  template:
    metadata:
      labels:
        app: afl-cba-customerinfo
    spec:
      containers:
      - name: afl-cba-customerinfo
        image: gcr.io/PROJECT_ID/IMAGE
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 256m
          limits:
            cpu: 256m
      - name: afl-cba-customerinfo-subscriber
        image: gcr.io/PROJECT_ID/SUBIMAGE
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
      - name: afl-cba-customerinfo-grpc
        image: gcr.io/PROJECT_ID/GRPCIMAGE
        ports:
        - containerPort: 5075
---
apiVersion: v1
kind: Service
metadata:
  name: afl-cba-customerinfo
  namespace: cba
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: grpc
      port: 5075
      targetPort: 5075

  selector:
    app: afl-cba-customerinfo



# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: Gateway
# metadata:
#   name: afl-cba-customerinfo-gateway
#   namespace: cba
# spec:
#   selector:
#     istio: ingressgateway # use istio default controller
#   servers:
#   - port:
#       number: 80
#       name: http
#       protocol: HTTP
#     hosts:
#     - accountofficer.afl.com
#     - customerinfo.afl.com
#     - verification.afl.com
#     - usermanagement.afl.com
#     - messaging.afl.com
#     - messageworker.afl.com

# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: afl-cba-customerinfo
#   namespace: cba
# spec:
#   hosts:
#   - customerinfo.afl.com
#   gateways:
#   - afl-cba-customerinfo-gateway
#   http:
#   - match:
#     route:
#     - destination:
#         port:
#           number: 80
#         host: afl-cba-customerinfo
