name: ZAP-API-SCAN

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Scan
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          token: ${{ secrets.ZAP_GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://merchant.test.9japay.com/auth/'
          cmd_options: '-a'