version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=afl-backofficeusermanagement
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
  api:
    container_name: backofficeusermanagement-api
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      DB_CLIENT: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: afl-backofficeusermanagement
    links:
      - db
    volumes:
      - ./:/src
volumes:
  db:
    driver: local
