apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- Deploy.yaml

images:
- name: REGISTRY/PROJECT_ID/IMAGE
  newName: swr.af-south-1.myhuaweicloud.com/afl-dev/afl/service-9japayoutward
- name: REGISTRY/PROJECT_ID/SUBIMAGE
  newName:  swr.af-south-1.myhuaweicloud.com/afl-dev/afl/service-9japayoutward-subscriber
